// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC7-qsl9vo6Tml5KEWkwUsdREQce5VyUBI',
    appId: '1:593814788917:web:62a6d015087d91f5294a7c',
    messagingSenderId: '593814788917',
    projectId: 'todoapp-fbb25',
    authDomain: 'todoapp-fbb25.firebaseapp.com',
    storageBucket: 'todoapp-fbb25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfBRc6pmkmOERfNOYBfywT_QeBMEw4FSM',
    appId: '1:593814788917:android:181d3219d0e16f5a294a7c',
    messagingSenderId: '593814788917',
    projectId: 'todoapp-fbb25',
    storageBucket: 'todoapp-fbb25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRuX4wRBX55pCoho9Fti8_IsvMQbgbcpE',
    appId: '1:593814788917:ios:46b14b48c02c4067294a7c',
    messagingSenderId: '593814788917',
    projectId: 'todoapp-fbb25',
    storageBucket: 'todoapp-fbb25.appspot.com',
    iosClientId: '593814788917-psvs78b52nqeu82ng56cpatqd803albk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRuX4wRBX55pCoho9Fti8_IsvMQbgbcpE',
    appId: '1:593814788917:ios:46b14b48c02c4067294a7c',
    messagingSenderId: '593814788917',
    projectId: 'todoapp-fbb25',
    storageBucket: 'todoapp-fbb25.appspot.com',
    iosClientId: '593814788917-psvs78b52nqeu82ng56cpatqd803albk.apps.googleusercontent.com',
    iosBundleId: 'com.example.todolist',
  );
}
